#!/bin/bash
# Grant permissions to GitHub Actions service principal for agent creation

echo "========================================================================"
echo "Grant Agent Creation Permissions"
echo "========================================================================"
echo ""
echo "The GitHub Actions service principal needs permission to create agents."
echo ""
echo "Run this command locally (replace with your values):"
echo ""
echo "# Get the service principal ID from AZURE_CREDENTIALS secret"
echo "# It's the 'clientId' field in your AZURE_CREDENTIALS JSON"
echo ""
echo "az role assignment create \\"
echo "  --assignee <YOUR-SERVICE-PRINCIPAL-CLIENT-ID> \\"
echo "  --role 'Cognitive Services OpenAI Contributor' \\"
echo "  --scope /subscriptions/$AZURE_SUBSCRIPTION_ID/resourceGroups/$AI_PROJECT_RESOURCE_GROUP/providers/Microsoft.CognitiveServices/accounts/$AI_PROJECT_NAME"
echo ""
echo "Or use the principal ID from the error message:"
echo "  Principal ID: b4d76bc7-7848-4345-8ff2-b0aa0a61d557"
echo ""
echo "az role assignment create \\"
echo "  --assignee b4d76bc7-7848-4345-8ff2-b0aa0a61d557 \\"
echo "  --role 'Cognitive Services OpenAI Contributor' \\"
echo "  --scope /subscriptions/$AZURE_SUBSCRIPTION_ID/resourceGroups/AI-RG/providers/Microsoft.CognitiveServices/accounts/davidsr-ai-project-resourcev2"
echo ""
echo "========================================================================"
